version: '3.8'

services:
  app:
    image: 'aptmgr.0.3'
    build:
      context: .
    container_name: aptmgr
    depends_on:
      - db
      - cache
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/aptmgr
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=P@ssw0rd
      - SPRING_DATA_REDIS_HOST=cache
      - SPRING_DATA_REDIS_PORT=6379
    ports:
      - "8083:8083"

  db:
    image: postgres:14.6-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=aptmgr
    ports:
      - "6541:5432"

  cache:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --bind 0.0.0.0