version: '3.8'

services:
  app:
    image: 'aptmgr.0.1'
    build:
      context: .
    container_name: aptmgr
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/aptmgr

    ports:
      - "8083:8083"

  db:
    image: postgres:14.6-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=aptmgr
    ports:
      - "6541:5432"