DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS properties;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS property_types;
DROP TABLE IF EXISTS roles;

CREATE TABLE roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL UNIQUE,
    password varchar NOT NULL
);

CREATE TABLE user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    FOREIGN KEY (role_id) REFERENCES roles(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE property_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type varchar NOT NULL
);

CREATE TABLE properties (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar NOT NULL,
    property_type_id bigint NOT NULL,
    owner_id bigint NOT NULL,
    FOREIGN KEY (property_type_id) REFERENCES property_types(id),
    FOREIGN KEY (owner_id) REFERENCES users(id)
);