DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS property;
DROP TABLE IF EXISTS property_types;

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    password varchar NOT NULL
);

CREATE TABLE property_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type varchar NOT NULL
);

CREATE TABLE property (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar NOT NULL,
    property_type_id bigint NOT NULL,
    FOREIGN KEY (property_type_id) REFERENCES property_types(id)
);

INSERT INTO property_types (type)
VALUES ('HOUSE'),
        ('APARTMENT');