CREATE TABLE IF NOT EXISTS property_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS properties (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar NOT NULL,
    property_type_id bigint NOT NULL,
    owner_uid varchar NOT NULL,
    build_in smallint,
    floors_numb smallint,
    sqr_meters smallint,
    last_payment timestamp WITHOUT TIME ZONE,
    monthly_paid bool,
    FOREIGN KEY (property_type_id) REFERENCES property_types(id)
);

CREATE TABLE IF NOT EXISTS property_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    img bytea NOT NULL,
    property_id bigint,
    FOREIGN KEY (property_id) REFERENCES properties(id)
);