server:
  port: 8083

spring:
  jpa:
    properties:
      hubernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aptmgr
    username: postgres
    password: P@ssw0rd
  thymeleaf:
    prefix: file:./target/classes/static/

---

spring:
  config:
    activate:
      on-profile: dev
server:
  port: 9001