spring:
  profiles:
    active: "dev"
server:
  port: 8083
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aptmgr
    username: postgres
    password: P@ssw0rd
  thymeleaf:
    prefix: file:./target/classes/static/
  security:
    jwt:
      secret-key: "d293df73b776119b4b78c6de9497925bd3697ef2b5a914e8c6fd8f3f4d13e327"
      expiration-time: 3600000
  data:
    redis:
      host: 192.168.1.92
      port: 6380
      time-to-live: 60000

---


spring:
  config:
    activate:
      on-profile: prod
  jpa:
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aptmgr
    username: postgres
    password: P@ssw0rd
  thymeleaf:
    prefix: file:./target/classes/static/
  security:
    jwt:
      secret-key: "d293df73b776119b4b78c6de9497925bd3697ef2b5a914e8c6fd8f3f4d13e327"
      expiration-time: 3600000
  data:
    redis:
      host: localhost
      port: 6379
      time-to-live: 60000
